(() => {
const s=document.currentScript;if(!s)return;const base=new URL(".",s.src);const here=decodeURIComponent(location.pathname).split("/Prompt-ria/")[1]||"index.html";const inInstrument=here.startsWith("Promptária/")&&here!=="Promptária/Index.html";const manifestURL=new URL(inInstrument?"../manifest.json":"manifest.json",base);
const css=document.createElement("style");css.textContent=`.neural-nav{position:sticky;top:0;z-index:9999;background:rgba(7,10,18,.94);backdrop-filter:blur(14px);border-bottom:1px solid rgba(117,137,176,.24);font:14px/1.4 system-ui,sans-serif}.neural-nav .bar{width:min(1180px,calc(100% - 22px));margin:auto;display:flex;gap:8px;align-items:center;flex-wrap:wrap;padding:9px 0}.neural-nav a,.neural-nav button{min-height:40px;padding:8px 11px;border:1px solid rgba(117,137,176,.3);border-radius:10px;background:rgba(255,255,255,.045);color:#f4f7ff;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;cursor:pointer}.neural-nav .brand{color:#4de7ff;font-weight:800;letter-spacing:.05em}.neural-nav form{display:flex;gap:7px;flex:1 1 360px}.neural-nav input{min-width:0;flex:1;background:#0b101b;color:#f4f7ff;border:1px solid rgba(117,137,176,.3);border-radius:10px;padding:9px 11px}.neural-nav form button{background:#4de7ff;color:#061016;font-weight:800}.neural-nav .meta{width:min(1180px,calc(100% - 22px));margin:auto;padding:0 0 8px;color:#8792aa;font-size:11px}.neural-nav .meta a{min-height:auto;padding:0;border:0;background:none;color:#8792aa}.neural-nav .ok{color:#4de7ff}.neural-nav .bad{color:#ff7f9f}.neural-results{display:none;width:min(1180px,calc(100% - 22px));margin:0 auto 10px;max-height:50vh;overflow:auto;background:#0c111d;border:1px solid #273149;border-radius:12px}.neural-results a{display:block;padding:11px 13px;border:0;border-bottom:1px solid #1d2637;border-radius:0}.neural-results small{display:block;color:#8792aa;margin-top:3px}@media(max-width:650px){.neural-nav form{flex-basis:100%}.neural-nav .brand{width:100%}}`;
document.head.appendChild(css);
const nav=document.createElement("div");nav.className="neural-nav";nav.innerHTML=`<nav class="bar" aria-label="Navegação neural"><a class="brand" data-home>◈ PROMPTÁRIA</a><a data-prev>← Anterior</a><a data-next>Próximo →</a><a data-main>⌂ Interface</a><form role="search"><input name="q" type="search" placeholder="Pesquisar em todos os instrumentos…" aria-label="Pesquisa transversal"><button>Pesquisar</button></form></nav><div class="meta"><span data-crumb>Conectando rede…</span> <span>•</span> <span data-status>rastreabilidade: verificando</span></div><div class="neural-results" data-results></div>`;
document.body.prepend(nav);
const home=nav.querySelector("[data-home]"),prev=nav.querySelector("[data-prev]"),next=nav.querySelector("[data-next]"),main=nav.querySelector("[data-main]"),form=nav.querySelector("form"),input=nav.querySelector("input"),results=nav.querySelector("[data-results]"),crumb=nav.querySelector("[data-crumb]"),status=nav.querySelector("[data-status]");
const href=p=>{if(p==="index.html")return new URL(inInstrument?"../../index.html":"../index.html",base).href;if(p==="Promptária/Index.html")return new URL(inInstrument?"../Index.html":"./Index.html",base).href;const rel=p.replace(/^Promptária\//,"");return new URL(inInstrument?"../"+rel:rel,base).href;};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function boot(){try{
const r=await fetch(manifestURL,{cache:"no-store"});if(!r.ok)throw Error("manifest HTTP "+r.status);
const m=await r.json(),items=m.instruments||[],by=new Map(items.map(x=>[x.path,x])),cur=by.get(here);
home.href=href("Promptária/Index.html");main.href=href("index.html");
if(cur){prev.href=href(cur.previous);next.href=href(cur.next);crumb.innerHTML=`Promptária / <a href="${home.href}">núcleo</a> / ${esc(cur.title)}`;}else{prev.style.display="none";next.style.display="none";crumb.textContent=here==="Promptária/Index.html"?"Promptária / núcleo de convergência":"Promptária / interface principal";}
const errors=items.filter(x=>!by.has(x.previous)||!by.has(x.next)||x.entry!==x.path);status.textContent=errors.length?`rastreabilidade: ${errors.length} relação(ões) a revisar`:`rastreabilidade: ${items.length} nós • entrada • retorno • ciclo • busca`;status.className=errors.length?"bad":"ok";
const indexed=await Promise.all(items.map(async x=>{try{const rr=await fetch(href(x.path),{cache:"no-store"});const h=await rr.text();return {...x,text:h.replace(/<script[\\s\\S]*?<\\/script>/gi," ").replace(/<style[\\s\\S]*?<\\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\\s+/g," ").trim()};}catch(e){return {...x,text:""}}}));
const normalize=s=>String(s||"").normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").toLocaleLowerCase().replace(/[^a-z0-9]+/g," ").trim(); const search=q=>{q=q.trim();results.innerHTML="";if(!q){results.style.display="none";return}const nq=normalize(q);const hits=indexed.map(x=>{const terms=[x.title,...(x.aliases||[]),...(x.capabilities||[])];const corpus=normalize(terms.join(" ")+" "+x.path+" "+x.text);let score=corpus.includes(nq)?100:0;if(normalize(x.title).includes(nq))score+=80;if((x.aliases||[]).some(a=>normalize(a).includes(nq)))score+=50;if((x.capabilities||[]).some(a=>normalize(a).includes(nq)))score+=35;if(normalize(x.text).includes(nq))score+=10;return {...x,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,30);results.innerHTML=hits.length?hits.map(x=>`<a href="${href(x.path)}">${esc(x.title)}<small>${esc(x.id)} • ${(x.capabilities||[]).slice(0,4).map(esc).join(" · ")}</small></a>`).join(""):'<div style="padding:14px;color:#8792aa">Nenhum instrumento ou contexto correspondente.</div>';results.style.display="block"};form.onsubmit=e=>{e.preventDefault();search(input.value)};input.oninput=()=>search(input.value);const q=new URLSearchParams(location.search).get("q");if(q){input.value=q;search(q)}
}catch(e){status.textContent="rastreabilidade: falha de catálogo";status.className="bad";crumb.textContent="Promptária / erro de integração"}}boot();
})();